### ISSUE TITLE
build for esp8266-nodemcu boot loop

### ISSUE THREAD

**Issue by danyboy666** [red-scorp/ag-panel#1]
I'm trying to compile this project for an esp8266mod module. The compilation is ok but i get this from the module once it is flashed. I get the same for a nodemcu board.

`
ets Jan 8 2013,rst cause:4, boot mode:(3,2)

load 0x4010f000, len 3584, room 16 tail 0 chksum 0xb0 csum 0xb0 v2843a5ac ~ld`

And similar output with other boards variants.

**Comment by red-scorp** [comment]
Hi @danyboy666 !

The ESP series of chips is not supported yet.
I have few similar boards in my cabinet. I'll have a look at this issue when I test it on my ESP boards. But it will not happens soon.

Best regards!

**Comment by danyboy666** [comment]
i'll try to find a way to boot this if I can. This something i would really like to run. Thanks for the answer i'll share what i can if i'm able to run this. Great project btw.

**Comment by red-scorp** [comment]
Yes, this would be a great help!

**Comment by red-scorp** [comment]
@danyboy666 : Hi! Any news on this one?

**Comment by danyboy666** [comment]
Closing this. I was busy with other projects.
